### ISSUE TITLE
Something wrong with 'click'

### ISSUE THREAD

**Issue by ajhstn** [evyatarmeged/Raccoon#1]
Hello good sir, i just downloaded and attempted to install this tool using the two documented methods, but am having issues.

### pip installer method

result: Did not install

`~$: pip install racoon-scanner
Collecting racoon-scanner
  Could not find a version that satisfies the requirement racoon-scanner (from versions: )
No matching distribution found for racoon-scanner
~$:`

### clone the repo method

result: issues with a module named 'click'

`Raccoon$: python3 raccoon_src/main.py
Traceback (most recent call last):
  File "raccoon_src/main.py", line 4, in <module>
    import click
ModuleNotFoundError: No module named 'click'
Raccoon$: pip install click
Requirement already satisfied: click in /usr/local/lib/python2.7/site-packages (6.7)
Raccoon$: python3 raccoon_src/main.py
Traceback (most recent call last):
  File "raccoon_src/main.py", line 4, in <module>
    import click
ModuleNotFoundError: No module named 'click'
Raccoon$:`

### My environment

`Raccoon$: pip --version
pip 18.0 from /usr/local/lib/python2.7/site-packages/pip (python 2.7)
Raccoon$: python --version
Python 2.7.15
Raccoon$: python3 --version
Python 3.7.0
`

`System Version: macOS 10.13.6 (17G65)
Kernel Version: Darwin 17.7.0`

**Comment by ajhstn** [comment]
I think i solved my own environment issues, namely, issues with conflicting python versions.

Case closed.

**Comment by shyamabc** [comment]
could you please help me 
I think i am also facing same issue

**Comment by ajhstn** [comment]
My issue was that even though i have python 3 installed, pip was still running under python 2.

Ensure you are running python 3+ and pip for python 3+

**Comment by evyatarmeged** [comment]
@ajhstn Also, there's a typo in the `pip install` - its supposed to be rac**c**oon scanner, not racoon-scanner =)
