### ISSUE TITLE
DNS mapping png file is broken in results

### ISSUE THREAD

**Issue by Khoramyar** [evyatarmeged/Raccoon#18]
When looking at the results folder, the "dns_mapping.png" file that supposed to be a download from dnsdumpster.com is a corrupt file and does not work.That is the case on every single scan I run.

Maye an issue in the fetch address?

**Comment by evyatarmeged** [comment]
Thanks for the heads up @Khoramyar. I'll look into it and update.

**Comment by Khoramyar** [comment]
Dear @evyatarmeged , thank you for the fix. It's working now. Please mark the issue closed.
