### ISSUE TITLE
Could not find Nmap or OpenSSL installed. Please install them and run Raccoon again.

### ISSUE THREAD

**Issue by backslash** [evyatarmeged/Raccoon#34]
I have both OpenSSL and Nmap running on my machine. I am running windows but for some reason whenever I attempt to start raccoon scanner I receive the same errors.  (Both of these tools are added to path)

**Comment by evyatarmeged** [comment]
Racoon scanner isn't supported for Windows, sorry.
Try using the containerized version :)

**Comment by uneame** [comment]
Hello, I have the same problem on termux.
