### ISSUE TITLE
Cannot get the "raccoon" command to work

### ISSUE THREAD

**Issue by Riley-Mattice** [evyatarmeged/Raccoon#37]

**Comment by evyatarmeged** [comment]
Which OS/Python version are you using ?
Also, what is the error when trying to run `raccoon --help`

**Comment by biswajitghosh21021983** [comment]
I am also getting the same error on Kali Linux ver 2020.04 and Python 3.8.2

**Comment by kaja-sudo** [comment]
sudo pip3 install raccoon-scanner
this command worked for me good luck

**Comment by Murphy1M** [comment]
> 
> 
> Which OS/Python version are you using ?
> Also, what is the error when trying to run `raccoon --help` ?


└─$ pip3 install raccoon_scanner 
Collecting raccoon_scanner
  Downloading raccoon_scanner-0.8.5-py3-none-any.whl (80 kB)
     |████████████████████████████████| 80 kB 4.5 MB/s 
Requirement already satisfied: dnspython in /usr/lib/python3/dist-packages (from raccoon_scanner) (2.0.0)
Requirement already satisfied: click in /usr/lib/python3/dist-packages (from raccoon_scanner) (7.1.2)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from raccoon_scanner) (2.25.1)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python3/dist-packages (from raccoon_scanner) (4.9.3)
Requirement already satisfied: lxml in /usr/lib/python3/dist-packages (from raccoon_scanner) (4.6.3)
Collecting fake-useragent
  Downloading fake-useragent-0.1.11.tar.gz (13 kB)
Requirement already satisfied: xmltodict in /usr/lib/python3/dist-packages (from raccoon_scanner) (0.12.0)
Requirement already satisfied: soupsieve>1.2 in /usr/lib/python3/dist-packages (from beautifulsoup4->raccoon_scanner) (2.2.1)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/lib/python3/dist-packages (from requests->raccoon_scanner) (1.7.1)
Building wheels for collected packages: fake-useragent
  Building wheel for fake-useragent (setup.py) ... done
  Created wheel for fake-useragent: filename=fake_useragent-0.1.11-py3-none-any.whl size=13487 sha256=7da71bac834db174da6b45c3037513560b4b579682d739b25af05e613e087ce7
  Stored in directory: /home/kali/.cache/pip/wheels/ae/e7/76/7dd44644d065268ab0e1b4fa2e802fa4bb0157717b7d6c6d92
Successfully built fake-useragent
Installing collected packages: fake-useragent, raccoon-scanner
  WARNING: The script raccoon is installed in '/home/kali/.local/bin' which is not on PATH.                                                               
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.                                       
Successfully installed fake-useragent-0.1.11 raccoon-scanner-0.8.5
                                                                             
┌──(mr㉿kali)-[~]
└─$ raccoon --help
raccoon: command not found


i'm using kali 2021.2

**Comment by Alisabir9** [comment]
tried everything but still getting same error


![raccoon installation error](https://github.com/evyatarmeged/Raccoon/assets/135224363/3f81d0a4-a4d9-4a5e-a225-9cae1bc6dc92)
