### ISSUE TITLE
enhancement: add to installation

### ISSUE THREAD

**Issue by kbroughton** [evyatarmeged/Raccoon#8]
on an ec2 amazon linux this was required:

sudo yum install git
git clone https://github.com/evyatarmeged/Raccoon.git
sudo yum install nmap
sudo yum install python3
sudo yum install gcc
sudo yum install libxml2-devel libxslt-devel python-devel
sudo pip3 install -r requirements.txt

**Comment by bhaizlett123** [comment]
I am trying to install on kali linux and i keep getting this error after running pip install -r requirements.txt

Traceback (most recent call last):
  File "raccoon_src/main.py", line 2, in <module>
    import asyncio
  File "/usr/local/lib/python2.7/dist-packages/asyncio/__init__.py", line 9, in <module>
    from . import selectors
  File "/usr/local/lib/python2.7/dist-packages/asyncio/selectors.py", line 39
    "{!r}".format(fileobj)) from None

**Comment by kbroughton** [comment]
I think that is a python version issue.  
python --version
should say python3.

**Comment by evyatarmeged** [comment]
Thanks @kbroughton. 
@bhaizlett123, you should try pip3 instead when you install. If you don't have it, get it with `sudo apt-get install python3-pip`.

@kbroughton, regarding the original issue, are you suggesting I add that to the README file ? there's a test that checks if openssl and nmap are installed and the README does mention it the required Python version is 3.5+.
If I misunderstood, I'd be happy to get some clarification :smile:

**Comment by kbroughton** [comment]
@evyatarmeged Regarding the original post, I was just suggesting that I needed more than just nmap openssl and python3.  So it might save others some time if you listed other items like
gcc libxml2-devel libxslt-devel python-devel (names may vary depending on linux distro)

**Comment by evyatarmeged** [comment]
Fair enough. I'll try to add a short remark on the next README update that on clean installations a little extra effort is required. 
After that, I'll close this issue.
